//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int PuntajeId { get; set; }
        public string UsuarioId { get; set; }
        public int Puntaje { get; set; }
        public string ColorFicha { get; set; }
        public int CantidadMovimientos { get; set; }
        public string EstadoPartida { get; set; }
        public string TipoPartida { get; set; }
        public System.DateTime FechaPartida { get; set; }
    }
}
