//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Usuarioid { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Usuario1 { get; set; }
        public string Contraseña { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Correo { get; set; }
        public int Pais { get; set; }
        public int EstadoId { get; set; }
        public Nullable<System.DateTime> FechaUltMod { get; set; }
    }
}
